-- begin SCHEDULE_TEACHER
create unique index IDX_SCHEDULE_TEACHER_UNIQ_EMAIL on SCHEDULE_TEACHER (EMAIL) ^
create index IDX_SCHEDULE_TEACHER_LAST_NAME on SCHEDULE_TEACHER (LAST_NAME)^
-- end SCHEDULE_TEACHER
-- begin SCHEDULE_LECTURE
alter table SCHEDULE_LECTURE add constraint FK_SCHEDULE_LECTURE_ON_TEACHER foreign key (TEACHER_ID) references SCHEDULE_TEACHER(ID)^
create index IDX_SCHEDULE_LECTURE_ON_TEACHER on SCHEDULE_LECTURE (TEACHER_ID)^
-- end SCHEDULE_LECTURE
