alter table SCHEDULE_LECTURE add constraint FK_SCHEDULE_LECTURE_ON_TEACHER foreign key (TEACHER_ID) references SCHEDULE_TEACHER(ID);
create index IDX_SCHEDULE_LECTURE_ON_TEACHER on SCHEDULE_LECTURE (TEACHER_ID);
